# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Deploy to Synology NAS

# Déclencheur du workflow
on:
  push:
    branches:
      - main  # Déclenche sur un push sur la branche main
      - dev   # Déclenche sur un push sur la branche dev

# Définition des jobs à exécuter
jobs:
  # Job pour le déploiement
  deploy:
    # Nom du job
    name: Deploy to NAS
    # IMPORTANT : Spécifie que ce job doit s'exécuter sur votre runner auto-hébergé
    runs-on: self-hosted

    # Étapes (steps) à exécuter
    steps:
      # 1. Configurer la clé SSH pour se connecter au NAS
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.NAS_IP }} >> ~/.ssh/known_hosts
        shell: bash

      # 2. Déployer sur l'environnement DEV si la branche est 'dev'
      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          ssh ${{ secrets.NAS_USER }}@${{ secrets.NAS_IP }} "
            echo '🚀 Déploiement sur DEV...'
            cd /volume1/docker/ggm-lb-dev
            echo '1. Mise à jour du code...'
            git pull
            echo '2. Reconstruction et redémarrage des conteneurs Docker...'
            sudo /usr/local/bin/docker compose down
            sudo /usr/local/bin/docker compose up -d --build
            echo '✅ Déploiement DEV terminé.'
          "
        shell: bash

      # 3. Déployer sur l'environnement PROD (S81) si la branche est 'main'
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh ${{ secrets.NAS_USER }}@${{ secrets.NAS_IP }} "
            echo '🚀 Déploiement sur PROD (S81)...'
            cd /volume1/docker/ggm-lb-s81
            echo '1. Mise à jour du code...'
            git pull
            echo '2. Reconstruction et redémarrage des conteneurs Docker...'
            sudo /usr/local/bin/docker compose down
            sudo /usr/local/bin/docker compose up -d --build
            echo '✅ Déploiement PROD (S81) terminé.'
          "
        shell: bash

